# This is a basic workflow to help you get started with Actions

name: Delete Runs

# Controls when the workflow will run
on:
  schedule:
    - cron: '15 2 */1 * *'

  workflow_dispatch:
    inputs:
        days:
          description: 'Number of days'
          required: true
          default: '15'
        minimum_runs:
          description: 'The minimum runs to keep for each workflow'
          required: true
          default: '6'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Delete workflow runs
  # You may pin to the exact commit or the version.
  # uses: Mattraks/delete-workflow-runs@8551bfa48c555325478b6ad32deed4287cae1500
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: ${{ github.event.inputs.days }}
          keep_minimum_runs: ${{ github.event.inputs.minimum_runs }}
