name: README Build
on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: "0 1 1 1 */1"

jobs:
  build:
    name: Update README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update README file
        uses: nclsbayona/images-link-action@master
        env:
          REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
